# Generated by Django 4.2.7 on 2024-01-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verify_code_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='670975', max_length=6, verbose_name='Код вeрификации'),
        ),
    ]
