# Generated by Django 4.2.7 on 2024-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='334752', max_length=6, verbose_name='Код вeрификации'),
        ),
    ]
