# Generated by Django 5.0 on 2023-12-19 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 19, 18, 51, 17, 248901), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_changed_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 19, 18, 51, 17, 248901), null=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена за единицу'),
        ),
    ]
