# Generated by Django 5.0 on 2023-12-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_changed_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Последнее изменение'),
        ),
    ]
