# Generated by Django 5.0 on 2023-12-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'name'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
